name: Build and push images to GHCR
on:
  push:
    branches:
      - main
    tags:
      - '*'
jobs:
  push-store-image:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub action'
        uses: actions/checkout@main

      - name: 'Build image'
        run: |
          make image

      - name: 'Login to GHCR'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Push image, latest'
        if: ${{ env.GITHUB_REF_TYPE != 'tag' }}
        run: |
          docker tag hello ghcr.io/googollee/hello-k8s-helm-flux:latest
          docker push ghcr.io/googollee/hello-k8s-helm-flux:latest

      - name: 'Push image, ${{ env.GITHUB_REF_NAME }}'
        if: ${{ env.GITHUB_REF_TYPE == 'tag' }}
        run: |
          docker tag hello ghcr.io/googollee/hello-k8s-helm-flux:${{ env.GITHUB_REF_NAME }}
          docker push ghcr.io/googollee/hello-k8s-helm-flux:${{ env.GITHUB_REF_NAME }}
