name: Build and push images to GHCR
on:
  push:
    branches:
      - main
    tags:
      - '*'
jobs:
  push-store-image:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub action'
        uses: actions/checkout@main

      - name: 'Check env'
        run: |
          echo ref type: ${GITHUB_REF_TYPE}, ${{ env.github.ref_type }}
          echo ref name: ${GITHUB_REF_NAME}, ${{ env.github.ref_name }}

      - name: 'Build image'
        run: |
          make image

      - name: 'Login to GHCR'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Push image, latest'
        run: |
          if [ "${GITHUB_REF_TYPE}" == "tag" ]
          then
            echo "not latest"
            exit 0
          fi
          docker tag hello ghcr.io/googollee/hello-k8s-helm-flux:latest
          docker push ghcr.io/googollee/hello-k8s-helm-flux:latest

      - name: 'Push image, with tag'
        run: |
          if [ "${GITHUB_REF_TYPE}" != "tag" ]
          then
            echo "not tag"
            exit 0
          fi
          docker tag hello ghcr.io/googollee/hello-k8s-helm-flux:${GITHUB_REF_NAME}
          docker push ghcr.io/googollee/hello-k8s-helm-flux:${GITHUB_REF_NAME}
